### PR TITLE
fixing minimal typo on examples/progamming-languages -> s/Rush/Rust/g

### PR DESCRIPTION
**Pull request by esparta**

### CODE REVIEW

**Comment by joelparkerhenderson** [comment]
Thanks good catch!

**Comment by esparta** [comment]
Thanks, @joelparkerhenderson !
It was kind of weird to me to read `"Rush can do nearly everything better"`, in my experience it's completely the opposite 😄

**Comment by joelparkerhenderson** [comment]
Your point is well-taken and a great example of why it's helpful for teams to do architecture decision records. Recently I'm seeing peers having good discussions of C++ versus Rust for new projects. What's your experience of these? I would like to create a new more-in-depth ADR that looks at these areas.

**Comment by esparta** [comment]
Oh English, my second language...

Sadly I was joking and now I have to explain I meant "(doing things in a) Rush can do nearly everything better".

**Pull request merged**
